# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniordesign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_update',
            field=models.IntegerField(null=True),
        ),
    ]
